server {
    listen 80;
    server_name snapshots.seudominio.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name snapshots.seudominio.com;

    ssl_certificate /etc/letsencrypt/live/snapshots.seudominio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/snapshots.seudominio.com/privkey.pem;

    client_max_body_size 1M;

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
